et
    Source = Excel.Workbook(File.Contents("C:\Users\julia\Downloads\190731-passagerarfrekvens-per-flygplats.xlsx"), null, true),
    ÄNGELHOLM_Sheet = Source{[Item="ÄNGELHOLM",Kind="Sheet"]}[Data],
    #"Changed Type" = Table.TransformColumnTypes(ÄNGELHOLM_Sheet,{{"Column1", type any}, {"Column2", type any}, {"Column3", type any}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type any}, {"Column9", type text}, {"Column10", type any}, {"Column11", type text}, {"Column12", type any}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type any}, {"Column23", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1", "Column2", "Column3", "Column8", "Column10", "Column12", "Column22", "Column20", "Column5",  "Column17", "Column21", "Column23"}),
    #"Transposed Table" = Table.Transpose(#"Removed Columns"),
    #"Removed Columns1" = Table.RemoveColumns(#"Transposed Table",{"Column1", "Column2", "Column3", "Column4", "Column5", "Column7", "Column9", "Column11", "Column12", "Column13", "Column30", "Column31", "Column32"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns1", "Custom", each if [Column14] = "Inrikes" then "Inrikes" else [Column15]),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"Column6", "Column8", "Column10", "Column14", "Custom", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns",{"Column15", "Column6", "Column29"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns2","",null,Replacer.ReplaceValue,{"Custom"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","",null,Replacer.ReplaceValue,{"Column14"}),
    #"Filled Down" = Table.FillDown(#"Replaced Value1",{"Column8", "Column10", "Column14", "Custom"}),
    #"Filtered Rows" = Table.SelectRows(#"Filled Down", each ([Custom] <> "Totalt Utrikes") and ([Column16] <> "Summa")),
    #"Added Custom1" = Table.AddColumn(#"Filtered Rows", "Anuar", each if [Column16] = "Ank" or [Column16] = "Avg" then [Column10] else "Auxiliar"),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Año", each if [Column16] = "Ank" or [Column16] = "Avg" then [Column8] else "Year"),
    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom2",{"Año", "Column8", "Anuar", "Column10", "Column14", "Custom", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns1",{"Column10", "Column8"}),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Columns3", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Year", type text}, {"Auxiliar", type text}, {"Utrikes", type text}, {"Europa", type text}, {"", type text}, {"Januari", type text}, {"Februari", type text}, {"Mars", type text}, {"April", type text}, {"Maj", type text}, {"Juni", type text}, {"Juli", type text}, {"Augusti", type text}, {"September", type text}, {"Oktober", type text}, {"November", type text}, {"December", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{ {"Auxiliar", "Airport"}}),
    #"Unpivoted Only Selected Columns" = Table.Unpivot(#"Renamed Columns", {"December", "November", "Oktober", "September", "Augusti", "Juli", "Juni", "Maj", "April", "Mars", "Januari", "Februari"}, "Attribute", "Value"),
    #"Replaced Value2" = Table.ReplaceValue(#"Unpivoted Only Selected Columns"," ","",Replacer.ReplaceText,{"Value"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value2",{{"Value", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"Utrikes", "Domestic/international"}, {"Europa", "International Loc"}, {"", "Depature/Arrival"}, {"Attribute", "Month"}, {"Value", "Passengers"}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Year", type text}})
in
    #"Changed Type3"
